Update repository references.
opensearch-project/sql-odbc pull request #30
Opened 2023-01-11 04:35 UTC by Yury-Fridlyand

Signed-off-by: Yury-Fridlyand [yury.fridlyand@improving.com](mailto:yury.fridlyand@improving.com)

### Description
Remove references to the main repo. Clean up some files and CI.
 
### Issues Resolved
Clean up repository migration
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-01-11 18:25 UTC, YANG-DB approved these changes

2023-01-11 18:30 UTC, YANG-DB requested changes
looking good - can u plz also add few words about that now this maven artifact is deployed into nexus ?
here - https://repo1.maven.org/maven2/org/opensearch/driver/opensearch-sql-jdbc/1.2.0.0/

2023-01-11 18:44 UTC, Yury-Fridlyand commented
@YANG-DB ODBC driver has no maven artifact. It is relevant for JDBC driver repo, but not ODBC.

2023-01-11 21:51 UTC, YANG-DB commented
correct - it was intended to the SQL repo - plz ignore ...

2023-01-27 18:05 UTC, YANG-DB approved these changes

2023-01-27 18:05 UTC, merged